# Generated by Django 3.0 on 2019-12-02 16:16
from django.db import migrations


def remove_null_webp_images(apps, schema_editor):
    WebPImage = apps.get_model('webp_converter', 'WebPImage')
    WebPImage.objects.filter(quality__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webp_converter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_null_webp_images),
    ]
