# Generated by Django 3.0 on 2019-12-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webp_converter', '0002_auto_20191202_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpimage',
            name='quality',
            field=models.PositiveIntegerField(),
        ),
    ]
